---
apiVersion: v2
appVersion: "1.10.0"
version: 1.0.0
name: apache-jena
description: A Helm chart for Apache Jena
type: application
home: "https://github.com/bhuwanupadhyay/helm-charts/tree/main/charts/apache-jena"
icon: "https://raw.githubusercontent.com/bhuwanupadhyay/helm-charts/main/images/apache-jena.png"
dependencies:
  - name: common
    version: 0.0.1
    repository: https://bhuwanupadhyay.github.io/helm-charts/
keywords:
  - Apache Jena
  - Semantic Web
sources:
  - https://github.com/apache/jena
maintainers:
  - name: bhuwanupadhyay
    email: hi@bhuwanupadhyay.com
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial release.
  artifacthub.io/images: |
    - name: template
      image: ghcr.io/bhuwanupadhyay/helm-charts:apache-jena-4.8.0
