---
apiVersion: v2
appVersion: "1.10.0"
version: 1.0.0
name: template
description: A Helm chart for Kubernetes
type: application
home: "https://github.com/bhuwanupadhyay/helm-charts/tree/master/charts/"
icon: "https://raw.githubusercontent.com/bhuwanupadhyay/helm-charts/master/images/template.png"
dependencies:
  - name: common
    version: 0.0.1
    repository: https://bhuwanupadhyay.github.io/helm-charts/
  - name: postgres
    version: 12.2.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgres.enabled
keywords:
  - foo
  - bar
sources:
  - foo
  - https://hub.docker.com/r/linuxserver/
maintainers:
  - name: bhuwanupadhyay
    email: hi@bhuwanupadhyay.com
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial release.
  artifacthub.io/images: |
    - name: template
      image: ghcr.io/linuxserver/template:0.1.0-ls1
