---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bhuwanupadhyay/helm-charts/tree/main/charts/common/values.yaml
#

image:
  repository: template
  pullPolicy: IfNotPresent
  tag: ""

secret: {}

# See more environment variables in the template documentation
# https://template.org/docs
env: {}
# TZ: ""

service:
  port:
    port: 80

ingress:
  enabled: false

persistence:
  config:
    enabled: false
    emptyDir: false
    mountPath: /config

# Enable postgres
# https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
postgresql:
  enabled: false
  global:
    postgresql:
      auth:
        postgresPassword: "template-postgres-pass"
        username: "template"
        password: "template-pass"
        database: "template-db"
