---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-envs
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  KC_DB: postgres
  KC_DB_URL: jdbc:postgresql://{{ include "common.names.fullname" . }}-postgresql:5432/{{ .Values.postgresql.global.postgresql.auth.database }}
  KC_DB_USER: {{ .Values.postgresql.global.postgresql.auth.username }}
