---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-envs
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
{{- if and .Values.postgresql.enabled }}
  KC_DB: postgres
  KC_DB_URL: jdbc:postgresql://{{ include "common.names.fullname" . }}-postgresql:5432/{{ .Values.postgresql.global.postgresql.auth.database }}
  KC_DB_USER: {{ .Values.postgresql.global.postgresql.auth.username }}
{{- end -}}
{{- if and .Values.externalDatabase.enabled }}
  KC_DB: {{ .Values.externalDatabase.type }}
  KC_DB_URL: jdbc:{{ .Values.externalDatabase.type }}://{{ .Values.externalDatabase.host }}:{{ .Values.externalDatabase.port }}/{{ .Values.externalDatabase.database }}
  KC_DB_USER: {{ .Values.externalDatabase.user }}
{{- end -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-envs
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
{{- if and .Values.postgresql.enabled }}
  KC_DB_PASSWORD: {{ .Values.postgresql.global.postgresql.auth.password | b64enc }}
{{- end -}}
{{- if and .Values.externalDatabase.enabled }}
  KC_DB_PASSWORD: {{ .Values.externalDatabase.password | b64enc }}
{{- end -}}
