---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.envSecretName }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  KC_DB_PASSWORD: {{ .Values.postgresql.global.postgresql.auth.password | b64enc }}
