apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgsync.fullname" . }}
  labels:
    {{- include "pgsync.labels" . | nindent 4 }}
data:
  schema.json: |-
    {{ .Values.pgsync.schemaJson }}
  schema.py: |-
    {{ .Values.pgsync.schemaPy }}
  data.py: |-
    {{ .Values.pgsync.dataPy }}
