---
apiVersion: v2
appVersion: "20.0.2"
version: 1.0.0
name: keycloak
description: A Helm chart for Keycloak
type: application
home: "https://github.com/bhuwanupadhyay/helm-charts/tree/main/charts/keycloak"
icon: "https://raw.githubusercontent.com/bhuwanupadhyay/helm-charts/main/images/keycloak.png"
dependencies:
  - name: common
    version: 0.0.1
    repository: https://bhuwanupadhyay.github.io/helm-charts/
  - name: postgresql
    version: 12.2.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
keywords:
  - keycloak
  - authentication
  - authorization
sources:
  - https://quay.io/repository/keycloak/keycloak
maintainers:
  - name: bhuwanupadhyay
    email: hi@bhuwanupadhyay.com
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial release.
  artifacthub.io/images: |
    - name: keycloak
      image: quay.io/keycloak/keycloak:20.0.5
