---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bhuwanupadhyay/helm-charts/tree/main/charts/common/values.yaml
#

image:
  repository: quay.io/keycloak/keycloak
  pullPolicy: IfNotPresent
  tag: ""

# Override the default args
args: ["start-dev"]

secret: { }

# See more environment variables in the template documentation
# https://template.org/docs
env:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  KC_PROXY: "edge"

envFrom:
- configMapRef:
    name: keycloak-envs
- secretRef:
    name: keycloak-envs

service:
  port:
    port: 8080

ingress:
  enabled: false

persistence:
  config:
    enabled: false
    emptyDir: false
    mountPath: /config

# Enable postgres
# https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
postgresql:
  enabled: true
  architecture: standalone
  global:
    postgresql:
      auth:
        postgresPassword: keycloak-postgres
        username: keycloak
        database: keycloak
        password: keycloak
