apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "apache-jena.fullname" . }}
  labels:
    {{- include "apache-jena.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
