version: '3.0'
services:
  fuseki:
    command: [ "--tdb2", "--update", "--loc", "/fuseki/databases", "/ds" ]
    build:
      context: .
      dockerfile: Dockerfile
    image: bhuwanupadhyay/fuseki
    ports:
      - "3030:3030"
    volumes:
      - logs:/fuseki/logs
      - databases:/fuseki/databases
volumes:
  databases:
  logs:

