version: '3.0'
services:
  fuseki:
    ## Example:
    ## command: [ "--tdb2", "--update", "--loc", "databases/DB2", "/ds" ]
    build:
      context: .
      dockerfile: Dockerfile
    image: fuseki
    ports:
      - "3030:3030"
    volumes:
      - ./logs:/fuseki/logs
      - ./databases:/fuseki/databases
#volumes:
