---
apiVersion: v1
kind: Namespace
metadata:
  name: helm-controller
  labels:
    name: helm-controller
---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-addons
  labels:
    name: kube-addons
