apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rdf-delta.fullname" . }}-fuseki
  labels:
    {{- include "rdf-delta.labels" . | nindent 4 }}
spec:
  {{- if not .Values.fusekiAutoscaling.enabled }}
  replicas: {{ .Values.fusekiReplicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rdf-delta.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rdf-delta.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rdf-delta.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "dcmd" ]
          args:
            - "fuseki"
            - "--port=3033"
            - "--conf=fuseki-config.ttl"
          ports:
            - name: http-fuseki
              containerPort: 3033
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http-fuseki
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          readinessProbe:
            tcpSocket:
              port: http-fuseki
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          volumeMounts:
            - mountPath: /fuseki/databases
              name: fuseki-databases
            - mountPath: /fuseki-config.ttl
              name: fuseki-config
              subPath: fuseki-config.ttl
            - mountPath: /log4j2.xml
              name: logging-config
              subPath: log4j2.xml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: fuseki-databases
          emptyDir: {}
        - name: fuseki-config
          configMap:
            name: {{ include "rdf-delta.fullname" . }}
        - name: logging-config
          configMap:
            name: {{ include "rdf-delta.fullname" . }}