{{- if .Values.fusekiAutoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "rdf-delta.fullname" . }}-fuseki
  labels:
    {{- include "rdf-delta.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "rdf-delta.fullname" . }}-fuseki
  minReplicas: {{ .Values.fusekiAutoscaling.minReplicas }}
  maxReplicas: {{ .Values.fusekiAutoscaling.maxReplicas }}
  metrics:
    {{- if .Values.fusekiAutoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.fusekiAutoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.fusekiAutoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.fusekiAutoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
