apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rdf-delta.fullname" . }}
  labels:
    {{- include "rdf-delta.labels" . | nindent 4 }}
stringData:
  password_file: |-
    admin: {{ .Values.fusekiAdminPassword }}