---
name: "Dockers: Release"

on:
  workflow_dispatch:
  push:
    branches: 
      - develop
    paths:
      - 'dockers/**'
      - '!dockers/**/README.md'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: List Subdirectories
        id: list_subdirectories
        run: |
          DIRECTORY_PATH="dockers"  # Replace with the actual path

          SUBDIRECTORIES=$(find "$DIRECTORY_PATH" -mindepth 1 -maxdepth 1 -type d -exec basename {} \;)

          echo "::set-output name=base_directory::$DIRECTORY_PATH"
          echo "::set-output name=subdirectories::$SUBDIRECTORIES"

      - name: Build and Push Docker Images
        run: |
          DIRECTORY_PATH=${{ steps.list_subdirectories.outputs.base_directory }}
          SUBDIRECTORIES=${{ steps.list_subdirectories.outputs.subdirectories }}

          for subdir in $SUBDIRECTORIES; do
            echo "Building and pushing Docker image in $subdir"
            REGISTRY=docker.io/${{ secrets.DOCKER_USERNAME }}
            IMAGE_NAME="$subdir"
            TAG="$(cat $DIRECTORY_PATH/$subdir/VERSION)"        
            docker buildx build \
              --push \
              --tag $IMAGE_NAME:$TAG ./$DIRECTORY_PATH/$subdir

            echo "Successfully built and pushed Docker image in $subdir"
          done